### ISSUE TITLE
Thoughts & suggestions...

### ISSUE THREAD

**Issue by boustanihani** [CleverCloud/demo-meteorjs#1]
I do not like the idea of not using `meteor build` (http://docs.meteor.com/#/full/meteorbuild) or similar tools like (https://github.com/onmodulus/demeteorizer) for apps in production. I am not aware of all optimizations and tweaks `meteor build` does, but it is for sure the official recommended way for bundling production code, so why not just use it...

Those are some discussions on this topic:
http://stackoverflow.com/questions/21316344/meteor-vs-meteor-bundle-for-production
http://stackoverflow.com/questions/28255934/meteor-run-production-with-mongo-url-vs-bundling

Looking at https://github.com/CleverCloud/demo-meteorjs/blob/master/start.sh#L10
`meteor --port 8080` should become => `meteor --port 8080 --production` in order to simulate the production mode (which minifies & bundles all .css & .js files...)

Extra configuration and caution is also needed for apps that use npm modules with tools like https://github.com/meteorhacks/npm

IMO, I think using **demeteorizer** (which is built on top of `meteor build`) is a good solution. After installing the demeteorizer, one could deploy to Clever-Cloud by editing & running this shell script (also works when using meteorhacks-npm):

```
# 1st install https://github.com/onmodulus/demeteorizer
# 2nd create some directory for the meteor-builds (preferably outside the project directory)
# And finally edit cleverdeploy.sh and run it from the meteor-project directory

formateddate=$(date +%Y.%m.%d_%H.%M.%S)
demeteorizer --app_name MyApp --output /home/username/pathToBuildDirectory/MyApp_"$formateddate"
cd /home/username/pathToBuildDirectory/MyApp_"$formateddate"
git init
git add -A
git commit -m "cleverdeploy"
git remote add clever git+ssh://git@push.par.clever-cloud.com/myAppId.git
git push clever master --force
```

**Comment by BlackYoup** [comment]
Thanks for these explanations, I totally missed the point of `meteor build`.

So I ran some tests this morning to use demeteorizer on our platform and this is a bit more complex. The script you suggested would work but I'm not sure it's the right way to do it. I don't think you should build the demeteorized app on your computer but you should just push on our platform the needed code for your application. Then, when it deploys, we will build and install your app.

So here is the script I made, it will be executed at `npm install` while `npm start` just starts your app:

```
#! /bin/bash

# Current path
currentPath=$(realpath ./)

# Install Meteorjs
curl https://install.meteor.com/ | sh
export PATH=/home/bas/.meteor:$PATH

# Install demeteorize
cd ~/ && npm install demeteorizer

# Go back to our project
cd "$currentPath"

# demeteorize the app
~/node_modules/.bin/demeteorizer -a "my_app" -o my_app/

# Go inside our demeteorized app to install modules
cd my_app/

# Install modules
npm install
```

Let me explain why I use `npm install` hook to install it and why I demeteorize the app in the same directory as the project:
When you trigger a deploy, the command that will install and start your app is `npm install &&
npm start`. Since a few weeks, we now have a feature that save the state of your app / files after these 2 steps. So if your app is redeployed or upscaled, we just have to copy the saved files and run `npm start`. For this project, a normal deploy took 46 seconds, a redeploy was 11 seconds.

You can find the update here : https://github.com/CleverCloud/demo-meteorjs/tree/demeteorizer
Give me your thoughts !

Note:  I didn't update the README.md for now, so check the `package.json` and `install.sh`

**Comment by boustanihani** [comment]
I assume that running the demeteorizer on my own machine is not an issue as long as the app depends on pure javascript modules with no need of compiling any binaries... but of course your solution is better :)

I just managed to deploy using your script. In my case I had to add 2 extra steps due to a known bug in meteorhacks-npm => https://github.com/meteorhacks/npm/issues/49

When using **meteorhacks-npm** one currently has to call  `meteor remove npm-container` and then `meteor run` once before starting the demeteorizer to avoid the error: `unknown package: npm-container`

In my case this is how **install.sh** looks like:

```
#! /bin/bash

# Current path
currentPath=$(realpath ./)

# Install Meteorjs
curl https://install.meteor.com/ | sh
export PATH=/home/bas/.meteor:$PATH

# Install demeteorize
cd ~/ && npm install demeteorizer

# Go back to our project
cd "$currentPath"

# Remove the npm-container so that it gets reinitialized again
# Fix for "Error: unknown package: npm-container"
# Check: https://github.com/meteorhacks/npm/issues/49
meteor remove npm-container

meteor run
# => Started proxy.
# => Creating container package for npm modules
# => please start your app again.
# => npm support has been initialized.

# demeteorize the app
~/node_modules/.bin/demeteorizer -a "my_app" -o my_app/

# Go inside our demeteorized app to install modules
cd my_app/

# Install modules
npm install
```

**Comment by BlackYoup** [comment]
Thanks for the update, your fix works fine.

Do you want to make a PR of these updates with an example of a required NPM package ? Plus a statement that says "Uncomment these lines only if you are using meteorhacks:npm package" ? :)

**Comment by boustanihani** [comment]
Sure I will :+1:

**Comment by boustanihani** [comment]
Here's a pull: https://github.com/CleverCloud/demo-meteorjs/pull/2

**Comment by BlackYoup** [comment]
Thank you :+1:

**Comment by boustanihani** [comment]
Welcome :)
